### ISSUE TITLE
Acceptance checklist for PR #197

### ISSUE THREAD

**Issue by pvalena** [developer-portal/content#199]
- [ ] correct image paths
- [ ] standalone section
- [ ] split to subsections
- [ ] fast-forward-able on master
- [ ] commit message reflects commit content
- [ ] unnecessary commits squashed
- [ ] jekyll header
- [x] copyright not included
- [ ] developer-friendly content

Information in detail can be found in [PRs discussion](https://github.com/developer-portal/content/pull/197#issuecomment-300479396) and in our [contribution guide](http://developer-portal.github.io/contributing/).

Please post any comments regarding the checklist here, but use the [PRs discussion](https://github.com/developer-portal/content/pull/197) to discuss the changes itself.
